version: '3.3'
services:
  mongo:
    image: mongo:4.2
    restart: always
    container_name: voitto_mongo_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: test
    ports:
      - 27017:27017
    volumes:
      - voitto-data:/data/db

  mongo-express:
    image: mongo-express:latest
    restart: always
    container_name: voitto_express_container
    ports:
      - 8080:8080
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb://admin:test@mongo:27017/
      ME_CONFIG_BASICAUTH: false

volumes:
  voitto-data:
