# ПОЛЬЗОВАТЕЛИ

## Создать нового пользователя

POST http://localhost:5002/api/users/register HTTP/1.1
content-type: application/json

{
  "name": "Ceavdari Grigori",
  "email": "ceavdari@gmail.com",
  "type": "admin",
  "password": "1771@grigori"
}

###

## Аутентификация  пользователя
POST http://localhost:5002/api/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "admin@admin.com",
  "password": "123@admin"
}
###

## Проверка пользователя
GET http://localhost:5002/users HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImJ1dG92QGdtYWlsLmNvbSIsIm5hbWUiOiJCdXRvdiBTIiwiYXZhdGFyIjoiZGVmYXVsdC1hdmF0YXIuanBnIiwidHlwZSI6InJlZ3VsYXIiLCJpZCI6IjY3MzM3MjczOThmZTU1M2Y3YmNmMTI2ZCIsImlhdCI6MTczNTE2Mzg1NiwiZXhwIjoxNzM1MjQ2NjU2fQ.-qTTg703IomQI-pDDC-oXEBaOxtnb8R9lfHlFv8TX50
###

## Загрузить изображение на аватар
POST http://localhost:5002/users/avatar HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImJ1dG92QGdtYWlsLmNvbSIsIm5hbWUiOiJCdXRvdiBTIiwiYXZhdGFyIjoiZGVmYXVsdC1hdmF0YXIuc3ZnIiwidHlwZSI6InJlZ3VsYXIiLCJpZCI6IjY2Mjc4NzgyZTNlYjZiOWIwNmNjODZjNyIsImlhdCI6MTcxMzg2Njc1MywiZXhwIjoxNzEzOTUzMTUzfQ.gEeWWWInZb7vqH5x3aqG7bAWFW0sBKYim8y5l_ug0kg
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="avatar.jpg"
Content-Type: image/jpeg

< /Users/Nikolay/Desktop/avatar.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--
###


# СКЛАД

## Добавление товара

POST http://localhost:5002/api/storehouse HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImJ1dG92QGdtYWlsLmNvbSIsIm5hbWUiOiJCdXRvdiBTIiwiYXZhdGFyIjoiZGVmYXVsdC1hdmF0YXIuanBnIiwidHlwZSI6InJlZ3VsYXIiLCJpZCI6IjY3MzM3MjczOThmZTU1M2Y3YmNmMTI2ZCIsImlhdCI6MTczNTE2Mzg1NiwiZXhwIjoxNzM1MjQ2NjU2fQ.-qTTg703IomQI-pDDC-oXEBaOxtnb8R9lfHlFv8TX50
content-type: application/json

{
  "name": "Куртка",
  "shortName": "50",
  "company": "Firma",
  "characteristics": "",
  "size": 50,
  "diameter": null,
  "type": "oxrana",
  "price": "",
  "isActive": true,
  "currentQuantity": 0
}

###

## Получение товаров

GET http://localhost:5002/api/storehouse HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImJ1dG92QGdtYWlsLmNvbSIsIm5hbWUiOiJCdXRvdiBTIiwiYXZhdGFyIjoiZGVmYXVsdC1hdmF0YXIuanBnIiwidHlwZSI6InJlZ3VsYXIiLCJpZCI6IjY3MzM3MjczOThmZTU1M2Y3YmNmMTI2ZCIsImlhdCI6MTczNTE2Mzg1NiwiZXhwIjoxNzM1MjQ2NjU2fQ.-qTTg703IomQI-pDDC-oXEBaOxtnb8R9lfHlFv8TX50
content-type: application/json
###


## Добавление операции с товаром

POST http://localhost:5002/api/storeoperation HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImJ1dG92QGdtYWlsLmNvbSIsIm5hbWUiOiJCdXRvdiBTIiwiYXZhdGFyIjoiZGVmYXVsdC1hdmF0YXIuanBnIiwidHlwZSI6InJlZ3VsYXIiLCJpZCI6IjY3MzM3MjczOThmZTU1M2Y3YmNmMTI2ZCIsImlhdCI6MTczNTE2Mzg1NiwiZXhwIjoxNzM1MjQ2NjU2fQ.-qTTg703IomQI-pDDC-oXEBaOxtnb8R9lfHlFv8TX50
content-type: application/json

{
  "productId": "6769661acf9e4f51a2e94b4d",
  "employeeId": "673a3d1e815cdd7335d7bbb1",
  "box": 2,
  "amount": 25,
  "totalAmount": 50,
  "typeOperation": "arrival",
  "fromWhom": "Володя"
}

###


# РАБОЧИЕ ЗАПИСЯМИ

## Получение рабочих записей
GET http://localhost:5002/jobs/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImJ1dG92QGdtYWlsLmNvbSIsIm5hbWUiOiJCdXRvdiBTIiwiYXZhdGFyIjoiaUJLSlJXS3pYUXgxakUzSjFhRHlKLmpwZWciLCJ0eXBlIjoicmVndWxhciIsImlkIjoiNjYyNzg3ODJlM2ViNmI5YjA2Y2M4NmM3IiwiaWF0IjoxNzE1MTg2OTAwLCJleHAiOjE3MTUyNzMzMDB9.1FwRY3x0BNm37SleVE5Xs6eThIXjXxupJSYDReGjcoA
Content-Type: application/json
###

## Создание рабочей записи
POST http://localhost:5002/jobs HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImJ1dG92QGdtYWlsLmNvbSIsIm5hbWUiOiJCdXRvdiBTIiwiYXZhdGFyIjoiZGVmYXVsdC1hdmF0YXIuanBnIiwidHlwZSI6InJlZ3VsYXIiLCJpZCI6IjY2NGRkYmZlMzA0MzdhMDEyMDhlYmViMSIsImlhdCI6MTcxNjM3ODYzOSwiZXhwIjoxNzE2NDY1MDM5fQ.RC2Jih-Oyd33_LlDGfsV7eNedcRgGKbojt3RPUWwqiY
Content-Type: application/json

{
  "employeeId": "664ddc4430437a01208ebeb9",
  "timeFrom": "2023-05-18T06:00:00.000Z",
  "timeTo": "2023-05-18T15:00:00.000Z",
  "detailId": "662e349aaf1fd8fce2d446a4",
  "typeOfJob": "kd",
  "extra": 5,
  "quantity": 24
}
###

## Обновление рабочей записи
PUT http://localhost:5002/jobs/662e67c688bfd28a06155c79 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImJ1dG92QGdtYWlsLmNvbSIsIm5hbWUiOiJCdXRvdiBTIiwiYXZhdGFyIjoiaUJLSlJXS3pYUXgxakUzSjFhRHlKLmpwZWciLCJ0eXBlIjoicmVndWxhciIsImlkIjoiNjYyNzg3ODJlM2ViNmI5YjA2Y2M4NmM3IiwiaWF0IjoxNzE0MzAyMTk4LCJleHAiOjE3MTQzODg1OTh9.c27Fo2n1PuVoo7_N_-ef55hxgEQUZUrapJk8C3zi1m8
Content-Type: application/json

{
  "timeTo": "2023-04-29T13:00:00.000Z"
}

###

## Удаление рабочей записи
DELETE http://localhost:5002/jobs/662e61330918ffddc3e68f33 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImJ1dG92QGdtYWlsLmNvbSIsIm5hbWUiOiJCdXRvdiBTIiwiYXZhdGFyIjoiaUJLSlJXS3pYUXgxakUzSjFhRHlKLmpwZWciLCJ0eXBlIjoicmVndWxhciIsImlkIjoiNjYyNzg3ODJlM2ViNmI5YjA2Y2M4NmM3IiwiaWF0IjoxNzE0MzAyMTk4LCJleHAiOjE3MTQzODg1OTh9.c27Fo2n1PuVoo7_N_-ef55hxgEQUZUrapJk8C3zi1m8

###



# РАБОЧИЕ

## Создание рабочего
POST http://localhost:5002/employees HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsIm5hbWUiOiJMaXphIFMiLCJhdmF0YXIiOiJYekNVbWRfaUYwdzR3ZTNlbVZKMHYucG5nIiwidHlwZSI6ImFkbWluIiwiaWQiOiI2NzI4ZmNiMmNlOGUzYjZkZWU3MmYyMjIiLCJpYXQiOjE3NjI4NTA5MTEsImV4cCI6MTc2MjkzMzcxMX0.u7YUl1dZK6bVdfcVHJUuaUCnTmqM-O74Imp6uoI2SoM
Content-Type: application/json

{
   "familyName": "Putin V duble",
   "registrationNumber": 1414,
   "mainJob": "kd"
}
###

## Получение рабочих
GET http://localhost:5002/api/employees HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsIm5hbWUiOiJMaXphIFMiLCJhdmF0YXIiOiJYekNVbWRfaUYwdzR3ZTNlbVZKMHYucG5nIiwidHlwZSI6ImFkbWluIiwiaWQiOiI2NzI4ZmNiMmNlOGUzYjZkZWU3MmYyMjIiLCJpYXQiOjE3NjI4NTA5MTEsImV4cCI6MTc2MjkzMzcxMX0.u7YUl1dZK6bVdfcVHJUuaUCnTmqM-O74Imp6uoI2SoM
###

## Удаление рабочего
DELETE http://localhost:5002/api/employees/673a3cce815cdd7335d7bba9 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsIm5hbWUiOiJMaXphIFMiLCJhdmF0YXIiOiJYekNVbWRfaUYwdzR3ZTNlbVZKMHYucG5nIiwidHlwZSI6ImFkbWluIiwiaWQiOiI2NzI4ZmNiMmNlOGUzYjZkZWU3MmYyMjIiLCJpYXQiOjE3NjI4MDYxNzEsImV4cCI6MTc2Mjg4ODk3MX0.yordLSyCy8ySzt8PPHxHc-D1sY6eSCgcEE_Hrnpf5SM
###

## Восстановление рабочего
PATCH http://localhost:5002/api/employees/recovery/673a3cce815cdd7335d7bba9 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsIm5hbWUiOiJMaXphIFMiLCJhdmF0YXIiOiJYekNVbWRfaUYwdzR3ZTNlbVZKMHYucG5nIiwidHlwZSI6ImFkbWluIiwiaWQiOiI2NzI4ZmNiMmNlOGUzYjZkZWU3MmYyMjIiLCJpYXQiOjE3NjI4NTA5MTEsImV4cCI6MTc2MjkzMzcxMX0.u7YUl1dZK6bVdfcVHJUuaUCnTmqM-O74Imp6uoI2SoM
###

## Обновление рабочего
PUT http://localhost:5002/api/employees/673a3d1e815cdd7335d7bbb1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsIm5hbWUiOiJMaXphIFMiLCJhdmF0YXIiOiJYekNVbWRfaUYwdzR3ZTNlbVZKMHYucG5nIiwidHlwZSI6ImFkbWluIiwiaWQiOiI2NzI4ZmNiMmNlOGUzYjZkZWU3MmYyMjIiLCJpYXQiOjE3NjI4NTA5MTEsImV4cCI6MTc2MjkzMzcxMX0.u7YUl1dZK6bVdfcVHJUuaUCnTmqM-O74Imp6uoI2SoM
Content-Type: application/json

{
   "familyName": "Antonov S",
   "registrationNumber": 65,
   "mainJob": "ma"
}

###



# ДЕТАЛИ

## Создание детали
POST http://localhost:5002/details HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImJ1dG92QGdtYWlsLmNvbSIsIm5hbWUiOiJCdXRvdiBTIiwiYXZhdGFyIjoiZGVmYXVsdC1hdmF0YXIuanBnIiwidHlwZSI6InJlZ3VsYXIiLCJpZCI6IjY2NGRkYmZlMzA0MzdhMDEyMDhlYmViMSIsImlhdCI6MTcxNjM3ODYzOSwiZXhwIjoxNzE2NDY1MDM5fQ.RC2Jih-Oyd33_LlDGfsV7eNedcRgGKbojt3RPUWwqiY
Content-Type: application/json

{
   "shortName": "503",
   "longName": "50383310",
   "normOfMinute": 50,
   "customer": "Zen"
}
###

##
GET http://localhost:5002/api/storeoperation/statistics HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsIm5hbWUiOiJMaXphIFMiLCJhdmF0YXIiOiJkZWZhdWx0LWF2YXRhci5qcGciLCJ0eXBlIjoiYWRtaW4iLCJpZCI6IjY3MjhmY2IyY2U4ZTNiNmRlZTcyZjIyMiIsImlhdCI6MTc0NTI0MDY1MiwiZXhwIjoxNzQ1MzIzNDUyfQ.HHIapHQX71QPUS_oicocAt4c1sejfTEx7RMihKnolzQ
content-type: application/json
###
